CREATE TABLE T_SYS_USR_MT_01 (
    C_UID INT NOT NULL,
    C_NM_FIRST VARCHAR(255),
    C_NM_LAST VARCHAR(255),
    C_PH_M_01 VARCHAR(20),
    C_PH_W_01 VARCHAR(20),
    C_ADDR_L1 VARCHAR(255),
    C_ADDR_L2 VARCHAR(255),
    C_ADDR_CIT VARCHAR(100),
    C_ADDR_STA VARCHAR(2),
    C_ADDR_ZIP VARCHAR(10),
    C_CR_DT VARCHAR(14), -- Needs TIMESTAMPTZ conversion
    C_LOGIN_CNT INT,
    C_LAST_IP VARCHAR(45),
    C_ROLE_BITS INT, -- Bitmask logic often needs normalization
    C_DEPT_CODE VARCHAR(10),
    C_MGR_UID INT,
    C_SALARY_AMT DECIMAL(18,2), -- Financial data mixed with profile data
    C_TAX_STATUS VARCHAR(5),
    C_EMERGENCY_CONTACT VARCHAR(255),
    CONSTRAINT PK_USR PRIMARY KEY (C_UID)
);

INSERT INTO T_SYS_USR_MT_01 (C_UID, C_NM_FIRST) VALUES (1, 'Legacy');